//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracksDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracks
    {
        public int Id { get; set; }
        public string TrackName { get; set; }
        public string AuthorName { get; set; }
    }
}
